### ISSUE TITLE
Please be clearer about the PSK ID

### ISSUE THREAD

**Issue by martinthomson** [tlswg/draft-ietf-tls-external-psk-importer#23]
The document says:
> Thus, importers induce no protocol changes with the exception of expanding the set of PSK identities sent on the wire.  

Aside from this statement needing update in light of the changes to the binder label, the core statement here isn't expanded upon.

The document needs to very clearly say that the PSK ID that is sent in the psk extension is *literally* the serialized content of `ImportedIdentity`.

**Comment by chris-wood** [comment]
Fixed in #24.
